"""Add game data and normalized articles

Revision ID: 4df412ef740a
Revises: None
Create Date: 2026-07-02 12:18:54.039964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4df412ef740a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=100), nullable=False, comment='Provider-native unique match tracking string identifier.'),
    sa.Column('sport', sa.Enum('NBA', 'NFL', name='sport_type_enum'), nullable=False),
    sa.Column('home_team', sa.String(length=50), nullable=False),
    sa.Column('away_team', sa.String(length=50), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'COMPLETED', 'POSTPONED', name='game_status_enum'), nullable=False),
    sa.Column('game_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'sport', name='uq_games_game_id_sport')
    )
    op.create_index(op.f('ix_game_data_away_team'), 'game_data', ['away_team'], unique=False)
    op.create_index(op.f('ix_game_data_game_datetime'), 'game_data', ['game_datetime'], unique=False)
    op.create_index(op.f('ix_game_data_game_id'), 'game_data', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_data_home_team'), 'game_data', ['home_team'], unique=False)
    op.create_index(op.f('ix_game_data_sport'), 'game_data', ['sport'], unique=False)
    op.create_index(op.f('ix_game_data_status'), 'game_data', ['status'], unique=False)
    op.create_table('normalized_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deterministic_id', sa.String(length=64), nullable=False, comment='Deterministic SHA-256 hash calculated from structural components to filter upstream duplicates.'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('source', sa.Enum('ESPN', 'HoopsHype', 'nba_api', 'nflreadpy', 'UNKNOWN', name='article_source_enum'), nullable=False),
    sa.Column('sport', sa.Enum('NBA', 'NFL', name='sport_type_enum'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deterministic_id', name='uq_articles_deterministic_id')
    )
    op.create_index(op.f('ix_normalized_articles_deterministic_id'), 'normalized_articles', ['deterministic_id'], unique=False)
    op.create_index(op.f('ix_normalized_articles_source'), 'normalized_articles', ['source'], unique=False)
    op.create_index(op.f('ix_normalized_articles_sport'), 'normalized_articles', ['sport'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_normalized_articles_sport'), table_name='normalized_articles')
    op.drop_index(op.f('ix_normalized_articles_source'), table_name='normalized_articles')
    op.drop_index(op.f('ix_normalized_articles_deterministic_id'), table_name='normalized_articles')
    op.drop_table('normalized_articles')
    op.drop_index(op.f('ix_game_data_status'), table_name='game_data')
    op.drop_index(op.f('ix_game_data_sport'), table_name='game_data')
    op.drop_index(op.f('ix_game_data_home_team'), table_name='game_data')
    op.drop_index(op.f('ix_game_data_game_id'), table_name='game_data')
    op.drop_index(op.f('ix_game_data_game_datetime'), table_name='game_data')
    op.drop_index(op.f('ix_game_data_away_team'), table_name='game_data')
    op.drop_table('game_data')
    # ### end Alembic commands ###